spring:
  application:
    name: gherkins.cucumber

  security:
    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: ${client-id}
#            client-secret: ${client-secret}
#            authorization-grant-type: authorization_code
#            scope: openid,profile,email
#            redirect-uri: ${oauth2-client-redirect-uri}
#        provider:
#          keycloak:
#            authorization-uri: ${oauth2-client-keycloak}/realms/${client-realm}/protocol/openid-connect/auth
#            token-uri: ${oauth2-client-keycloak}/realms/${client-realm}/protocol/openid-connect/token
#            user-info-uri: ${oauth2-client-keycloak}/realms/${client-realm}/protocol/openid-connect/userinfo
#            issuer-uri: ${oauth2-client-keycloak}/realms/${client-realm}
#            jwk-set-uri: ${oauth2-client-keycloak}/realms/${client-realm}/protocol/openid-connect/certs
#            user-name-attribute: preferred_username

      resource-server:
        jwt:
          issuer-uri: ${oauth2-client-keycloak}/realms/${client-realm}


logging:
  level:
    root: debug

